# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 8
  MaximumLineLength:
    maxLineLength: 150
  NoWildcardImports:
    active: false

style:
  WildcardImport:
    excludeImports:
      - 'com.intellij'
  MaxLineLength:
    maxLineLength: 150