# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  NoWildcardImports:
    active: false
  Indentation:
    continuationIndentSize: 8
  MaximumLineLength:
    maxLineLength: 150

style:
  WildcardImport:
    excludeImports:
      - 'com.intellij.*'
  MaxLineLength:
    maxLineLength: 150